<?php
/**
 * Created by PhpStorm.
 * User: sovkutsan
 * Date: 2/9/18
 * Time: 4:17 PM
 */

namespace AppBundle\Admin;


use AppBundle\Entity\BlogPost;
use AppBundle\Entity\Product;
use Sonata\AdminBundle\Admin\AbstractAdmin;
use Sonata\AdminBundle\Datagrid\DatagridMapper;
use Sonata\AdminBundle\Datagrid\ListMapper;
use Sonata\AdminBundle\Form\FormMapper;
use Sonata\AdminBundle\Form\Type\ModelType;

class ProductAdmin extends AbstractAdmin
{
    protected function configureFormFields(FormMapper $formMapper)
    {
        $formMapper
            ->add('name', 'text')
            ->add('price', 'number')
            ->add('description', 'textarea')
            ->add('file', 'file', [
                'required' => false
            ]);
        /*->add('category', 'sonata_type_model', [
                'class' => 'AppBundle\Entity\Category',
                //'choice_label' => 'name'
                'property' => 'name'
            ])*/
    }

    public function prePersist($object)
    {
        $this->manageFileUpload($object);
        //parent::prePersist($object); // TODO: Change the autogenerated stub
    }
    public function preUpdate($object)
    {
        $this->manageFileUpload($object);
        //parent::preUpdate($object); // TODO: Change the autogenerated stub
    }
    private function manageFileUpload($image) {
        if($image->getFile()) {
            $image->refreshUpdated();
        }
    }


    protected function configureDatagridFilters(DatagridMapper $datagridMapper)
    {
        $datagridMapper
            ->add('name')
            /*->add('category', null, [], 'entity', [
                    'class' => 'AppBundle\Entity\Category',
                    'choice_label' => 'name'
                ]
            )*/
        ;
    }

    protected function configureListFields(ListMapper $listMapper)
    {
        $listMapper
            ->addIdentifier('name')
            ->add('pic')
            ;
    }

    public function toString($object)
    {
        return $object instanceof Product ?
            $object->getName() : 'Product';
    }
}